config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'

  get 'users/show'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  root to: "home#index"

  post 'makeAdmin' => 'users#make_admin'

    resources :badges

end

app/models/ability.rb
class Ability

  include CanCan::Ability

  def initializer(user)
    if user.role == "admin"
      can :create, Badge
    else
      can :read, :all
    end
  end
end

app/models/badge.rb
class Badge < ActiveRecord::Base

  belongs_to :user

  validates_presence_of :name, :user_id

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:linkedin]

  has_many :badges

  validates_presence_of :name

def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
  end
end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    session["user_return_to"] || users_show_path
  end

  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    end

end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController

  before_action :authenticate_user!

  def new
    if current_user.role == "admin"
      @badge = Badge.new
      # @user_list = User.all
    else
      redirect_to '/users/show'
    end
  end

  def create
    @badge = Badge.new(badge_params)
    @badge.name = @badge.name.downcase
    @user = User.find(params[:badge][:user])
    @badge.user_id = @user.id
    if @badge.save
      flash[:notice] = "Success"
      redirect_to '/users/show'
    else @badge.delete
      flash[:notice] = "Error! Something went wrong"
      redirect_to '/users/show'
    end
  end

  def badge_params
    params.require(:badge).permit(:name)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def update

    account_update_params = devise_parameter_sanitizer.sanitize(:account_update)

    if account_update_params[:password].blank?
      account_update_params.delete("password")
      account_update_params.delete("password_confirmation")
    end

    @user = User.find(current_user.id)
    if @user.update_attributes(account_update_params)
      flash[:notice] = 'Thank you! Your profile has been successfully updated.'
      sign_in @user, :bypass => true
      redirect_to users_profile_path
    else
      render "edit"
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def linkedin
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "linkedin") if is_navigational_format?
    else
      session["devise.linkedin_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def show
    @my_badges = []
    @my_badges = Badge.where(:user_id => current_user.id)
    @all_badges = Badge.last(3).reverse
  end

  def profile
    @my_badges = Badge.where(:user_id => current_user.id)
    @all_badges = Badge.all
    @all_badges.reverse
  end

  def make_admin
    if @admin = User.find(params[:name])
      @admin.role = 'admin'
      @admin.save
      flash[:notice] = "You have created a new Admin."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/badges_helper.rb
module BadgesHelper

  def badge_recipient_name(badge)
    User.find(badge.user_id).name
  end

  def badge_name(badge)
    badge.name.titleize
  end

  def badge_award_date(badge)
    badge.created_at.strftime("%B %d, %Y")
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def show_last_six_rewards_reward(user, number)
    if @my_badges[-number]
      "#{@my_badges[-number].name.titleize}"
    end
  end

  def show_last_six_rewards_date(user, number)
    if @my_badges[-number]
      "#{@my_badges[-number].created_at.strftime("%d %B %Y")}"
    end
  end

  def days_since_last_reward(user)
    if @my_badges.any?
      difference = Time.now - (@my_badges[-1].created_at)
    else
      difference = Time.now - user.created_at
    end
      (((difference/60)/60)/24).floor
  end

  def total_number_of_rewards(user)
    @my_badges.length
  end

  def most_popular_reward(user)
    @reward_names = []
    @my_badges.each do |badge|
      @reward_names << badge.name
    end
    @result = Hash.new(0)
    @reward_names.each {|reward| @result[reward] += 1}
    @result.max_by{|k,v| v}[0].titleize
  end

  def count_of_most_popular_reward(user)
    @reward = most_popular_reward(user)
    @counter = 0
    @my_badges.each do |badge|
      @counter += 1 if badge.name.titleize == @reward
    end
    @counter
  end

  def show_recent_reward_employee(array_index)
    @badge_recipient = User.find(@all_badges[array_index].user_id)
    "#{@badge_recipient.name}"
  end

  def show_recent_reward_name(array_index)
    @badge_recipient = User.find(@all_badges[array_index].user_id)
    "#{@all_badges[array_index].name.titleize}"
  end

  def show_recent_reward_date(array_index)
    @badge_recipient = User.find(@all_badges[array_index].user_id)
    "#{@all_badges[array_index].created_at.strftime("%d %B %Y")}"
  end

  def reward_image(reward)
    @images = ['/images/angel.png', '/images/sales.png', '/images/customer.png', '/images/hardworker.png', '/images/team.png', '/images/leanonme.png']
    @reward = ['Office Angel', 'Top Sales Person', 'Outstanding Customer Service', 'Grafter', 'Team Player', 'Lean On Me']
    if @reward.include?(reward)
      @position = @reward.index(reward)
      @images[@position.to_i]
    else
      '/images/rewardicon-01.png'
    end
  end


end

app/views/badges/new.html.erb
<section class="wrapbadgepage">
  <section class="holderbadgepage">
    <section class="navbar">
      <a href="/users/show"><img src="/images/logo-01.png" class="navlogo"></a>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "signoutnav" %>
      <%= link_to 'Dashboard', users_show_path, class: 'signoutnav' %>
      <section class="avatar-square">
        <a href="/users/profile"><section class="avatarnav"></section></a>
      </section>
    </section>
    <section class="main-body">
      <section class="main-preset">
        <section class="preset-holder">
          <section class="reward-heading">Reward your Employees</section><br><br><br>
            <section id='built_in_badges'>
              <section class="selection-form-custom">
                <%= form_for @badge do |f| %>
                  <%= f.label :select_an_employee, class: "employee" %><br>
                  <section class="dropdown">
                    <%= f.collection_select :user, User.all, :id, :name %>
                  </section>
                  <%= f.hidden_field :name %>
                  <section class="submit">
                    <%= f.submit 'Reward', class: 'submit_style' %>
                  </section>
                <% end %>
              </section>
              <section class="rewarding">
                  <section class="reward">
                    <img src='/images/mail-01.png' id="reward_image"/>
                  </section>
                  <section class="button">Next Reward</section>
              </section>
            </section>
        </section>
      </section>

      <section class="main-custom">
        <section class="custom-holder">
          <section id='custom_badges'>
            <section class="custom-heading">Create your own</section><br><br><br>
              <section class="custom-badges-form">
                <%= form_for @badge do |f| %>
                  <%= f.label :select_an_employee, class: "employee" %><br><br>
                  <section class="dropdownarea">
                    <%= f.collection_select :user, User.all, :id, :name, class: "dropdown" %>
                  </section><br>
                  <section id="name">
                    <%= f.text_field :name, placeholder: "Custom Reward Name", class: 'boxstyle' %>
                  </section><br>
                  <section class="submit1">
                    <%= f.submit 'Reward', class: 'submit_style' %>
                  </section>
                <% end %>
              </section>
          </section>
      </section>
    </section>

  </section>
</section>

app/views/home/index.html.erb
<section class="flash">
  <section id="notice"><%= notice %></section>
  <section id="alert"><%= alert %></section>
</section>
<section class="wrap">
	<section class="holder">
		<section class="nav">

			<a href="https://github.com/HatStephens/FATS_Rewardr"><img id="logo" src="/images/logo-01.png"></a>

			<a href="users/sign_in">
				<section id="login">
					<p id="logintext"><span class="small">Existing User</span> Login</p>
				</section>
			</a>

			<a href="users/sign_up">
				<section id="signup">
					<p id="signuptext1"><span class="small">New User</span> Sign up</p>
				</section>
			</a>

		</section>

		<section id="caption">
			Reward your employees
		</section>

		<h3 id="caption2">
			Get an unlimited private rewarding system and one-to-one appreciations, forever.<br>
			Private team plans begin from £5 per month.
		</h3>

		<section class="link">
			<a href="users/auth/linkedin">
				<section id="linkedinbutton" href="users/auth/linkedin">
					<img id="linkedinimg" src="/images/linked-01.png">
					<section id="linkedintext">Sign in with LinkedIn</section>
				</section>
			</a>
		</section><br><br>

		<section id="terms1">By signing up you agree to our <u>Terms and Conditions</u></section>
	</section>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RewardR</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//use.typekit.net/mqc5gvv.js"></script>
  <script>try{Typekit.load();}catch(e){}</script>
</head>
<body>

  <%= yield %>

</body>
</html>

app/views/users/profile.html.erb
<section class="wrapbadgepage">

  <section class="holderbadgepage">

    <section class="navbar">
      <a href="/users/show"><img src="/images/logo-01.png" class="navlogo"></a>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "signoutnav" %>
      <%= link_to 'Dashboard', users_show_path, class: 'signoutnav' %>
      <%= link_to 'Edit Profile', edit_user_registration_path, class: 'signoutnav'%>
      <span class="pic"><a href="/users/profile"><section class="avatarnav"></section></a>
      <% if current_user.role == 'admin' %>
        <%= link_to 'Reward Employee', new_badge_path, class: "signoutnav" %>
      <% end %>

    </section>

  <br />
  <br />
  <br />
  <br />
  <br />

  <p id='profile-flash-notice'><%= notice %></p>

  <h1 id='h1-profile-page-name'><%= current_user.name %>'s Profile</h1>
  <% if current_user.role == 'admin' %>
    <h2 id='h2-profile-page-name'>Admin <a href='#' id='add-admin'>(Add Admin)</a></h2>
    <section id='admin-management'>
      <%= collection_select :post, :user, User.all, :id, :name %>&nbsp&nbsp<a href='#' id='make-admin'>Make Admin</a>
      <p id='admin-result'></p>
    </section>
  <% end %>

  <section id='profile-page-container'>

    <section id='my-badges-archive' class='profile-page-information-box'>

    <h2 class='h2-header-title'>MY REWARD ARCHIVE</h2>

    <section class="listofbadges">
      <% if @my_badges.any? %>
      <ul id='badge-archive'>
      </section>

      <% @my_badges.each do |badge| %>
        <li class='li-award-entry'><img src=<%= reward_image(badge_name(badge)) %> alt='Small icon of badge' class="rewardiconprofile"/><%= badge_name(badge) %> rewarded on <%= badge_award_date(badge) %></li>
      <% end %>
      </ul>

    <% else %>
<br>
      You have not won any badges yet!

    <% end %>

    </section>

    <section id='recent-news' class='profile-page-information-box'>

      <h2 class='h2-header-title'>RECENT NEWS</h2>

      <section class="listofbadges"><% if @all_badges.any? %></section>

        <ul id='recent-badges-awarded'>
          <% @all_badges.each do |badge| %>
            <li class='li-award-entry'><img class="rewardiconprofile" src=<%= reward_image(badge_name(badge)) %> alt='Small icon of badge' />&nbsp&nbsp&nbsp<b><%= badge_recipient_name(badge) %></b> earned the <%= badge_name(badge) %> reward on <%= badge_award_date(badge) %></li>
          <% end %>
        </ul>

      <% else %>

        There are no recent news items!

      <% end %>

    </section>


  </section>

</section>

app/views/users/show.html.erb
<head>

</head>

<html>

<body>

  <section id="mainbody">

  <section class="navbar">
      <a href="/users/show"><img src="/images/logo-01.png" class="navlogo"></a>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "signoutnav" %>
      <a href="/users/profile"><section class="avatarnav"></section></a>
      <% if current_user.role == 'admin' %>
        <%= link_to 'Reward Employee', new_badge_path, class: "signoutnav" %>
      <% end %>

    </section>

      <section id="tileswrap">

        <section id="topwrap">

          <section class="tileheader">
            <h1 class="headertitle">Your Statistics</h1>
          </section>

            <section id="tile1">
              <section class="infotile">
                <section class="topnumbertiles">
                  <img class="rewardicon" src="/images/rewardicon-01.png">
                  <h4><%= days_since_last_reward(current_user) %></h4>
                  <p>day(s) ago</p>
                </section>
                  <section class="toptexttiles">
                    <h3>DAYS SINCE LAST REWARD</h3>
                  </section>
              </section>
            </section>

            <section id="tile2">
              <section class="infotile">
                <section class="topnumbertiles">
                  <% if @my_badges.any? %>
                    <img class="rewardicon" src=<%= reward_image(most_popular_reward(current_user)) %>>
                    <h4><%= most_popular_reward(current_user) %> </h4>
                    <p><%= count_of_most_popular_reward(current_user) %> time(s) awarded</p>
                  <% else %>
                    <img class="rewardicon" src='/images/rewardicon-01.png'>
                  <% end %>
                </section>
                  <section class="toptexttiles">
                    <h3>MOST REWARDED REWARD</h3>
                  </section>
              </section>
            </section>

            <section id="tile3">
              <section class="infotile">
                <section class="topnumbertiles">
                  <% if @my_badges.any? %>
                  <img class="rewardicon" src="/images/rewardicon2-01.png">
                  <h4><%= total_number_of_rewards(current_user) %></h4>
                  <p>rewards in total</p>
                  <% else %>
                    <img class="rewardicon" src='/images/rewardicon-01.png'>
                  <% end %>
                  
                </section>
                  <section class="toptexttiles">
                    <h3>TOTAL NUMBER OF REWARDS</h3>
                  </section>
              </section>
            </section>

    </section>

    <!-- MIDDLE ROW  -->

    <section id ="middlewrap">

      <section class="tileheader">
            <h1 class="headertitle">My Latest Rewards</h1>
          </section>

    <section id="tile4">
      <section class="infotile">
        <section class="middlebadgetiles">
          <% if @my_badges.length > 0 %>
          <img class="rewardicon" src=<%= reward_image(show_last_six_rewards_reward(current_user, 1)) %>>
            <h4><%= show_last_six_rewards_reward(current_user, 1) %></h4>
            <p><%= show_last_six_rewards_date(current_user, 1) %></p>
          <% else %>
            <img class="rewardicon" src='/images/rewardicon-01.png'>
            <h2>There is no reward</h2>
          <% end %>
        </section>
          <section class="middletexttiles">
            <h3>LATEST REWARD</h3>
          </section>
      </section>
    </section>

    <section id="tile5">
      <section class="infotile">
        <section class="middlebadgetiles">
          <% if @my_badges.length > 1 %>
          <img class="rewardicon" src=<%= reward_image(show_last_six_rewards_reward(current_user, 2)) %>>
             <h4><%= show_last_six_rewards_reward(current_user, 2) %></h4>
            <p><%= show_last_six_rewards_date(current_user, 2) %></p>
          <% else %>
            <img class="rewardicon" src='/images/rewardicon-01.png'>
            <h2>There is no reward</h2>
          <% end %>
        </section>
          <section class="middletexttiles">
            <h3>LATEST REWARD</h3>
          </section>
      </section>
    </section>

      <section id="tile6">
        <section class="infotile">
          <section class="middlebadgetiles">
          <% if @my_badges.length > 2 %>
            <img class="rewardicon" src=<%= reward_image(show_last_six_rewards_reward(current_user, 3)) %>>
            <h4><%= show_last_six_rewards_reward(current_user, 3) %></h4>
            <p><%= show_last_six_rewards_date(current_user, 3) %></p>
          <% else %>
            <img class="rewardicon" src='/images/rewardicon-01.png'>
            <h2>There is no reward</h2>
          <% end %>
        </section>
        <section class="middletexttiles">
          <h3>LATEST REWARD</h3>
        </section>
      </section>
    </section>

  </section>

    <!-- BOTTOM ROW -->

    <section id="bottomwrap">

      <section class="tileheader">
            <h1 class="headertitle">Latest Co-Worker Rewards
          </section>

    <section id="tile7">
      <section class="infotile">
        <section class="bottombadgetiles">
          <% if @all_badges.length > 0 %>
            <img class="rewardicon" src=<%= reward_image(show_recent_reward_name(0)) %>>
            <h2><%= show_recent_reward_employee(0) %></h2>
            <p><b><%= show_recent_reward_name(0) %></b></p>
            <p><%= show_recent_reward_date(0) %></p>
          <% else %>
            <img class="rewardicon" src='/images/rewardicon-01.png'>
          <% end %>
        </section>
          <section class="bottomtexttiles">
            <h3>RECENT REWARD</h3>
          </section>
      </section>
    </section>

    <section id="tile8">
      <section class="infotile">
        <section class="bottombadgetiles">
          <% if @all_badges.length > 1 %>
            <img class="rewardicon" src=<%= reward_image(show_recent_reward_name(1)) %>>
            <h2><%= show_recent_reward_employee(1) %></h2>
            <p><%= show_recent_reward_name(1) %></p>
            <p><%= show_recent_reward_date(1) %></p>
          <% else %>
            <img class="rewardicon" src='/images/rewardicon-01.png'>
          <% end %>
        </section>
          <section class="bottomtexttiles">
            <h3>RECENT REWARD</h3>
          </section>
      </section>
    </section>

    <section id="tile9">
      <section class="infotile">
        <section class="bottombadgetiles">
          <% if @all_badges.length > 2 %>
            <img class="rewardicon" src=<%= reward_image(show_recent_reward_name(2)) %>>
            <h2><%= show_recent_reward_employee(1) %></h2>
            <p><%= show_recent_reward_name(1) %></p>
            <p><%= show_recent_reward_date(1) %></p>
          <% else %>
            <img class="rewardicon" src='/images/rewardicon-01.png'>
          <% end %>
        </section>
          <section class="bottomtexttiles">
                        <h3>RECENT REWARD</h3>
          </section>
      </section>
    </section>

  </section>
</section>

</section>

</body>

</html>